/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message and get a full response
         * @description Invoke the agent and return the complete response as JSON.
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message and stream the response via SSE
         * @description Invoke the agent and stream events back as Server-Sent Events.
         *
         *     Each SSE event has one of the following types:
         *
         *     - ``agent``       — agent switch, data: ``{"agent": "...", "from": "..."}``
         *     - ``tool_call``   — tool invocation started, data:
         *                         ``{"tool": "...", "args": {...}, "agent": "..."}``
         *     - ``tool_result`` — tool finished, data:
         *                         ``{"tool": "...", "result": "...", "agent": "..."}``
         *     - ``token``       — a partial text token from the model
         *     - ``done``        — final event, data: ``{"thread_id": "..."}``
         *     - ``error``       — data: ``{"detail": "..."}``
         */
        post: operations["chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available LLM providers and their models
         * @description Return all configured LLM providers with their dynamically discovered models.
         */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        /** Update Project */
        put: operations["update_project_api_projects__project_id__put"];
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/test-scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Scenarios */
        get: operations["list_test_scenarios_api_projects__project_id__test_scenarios_get"];
        put?: never;
        /** Create Test Scenario */
        post: operations["create_test_scenario_api_projects__project_id__test_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Test Scenario */
        get: operations["get_test_scenario_api_test_scenarios__scenario_id__get"];
        /** Update Test Scenario */
        put: operations["update_test_scenario_api_test_scenarios__scenario_id__put"];
        post?: never;
        /** Delete Test Scenario */
        delete: operations["delete_test_scenario_api_test_scenarios__scenario_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-scenarios/{scenario_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs By Scenario */
        get: operations["list_runs_by_scenario_api_test_scenarios__scenario_id__runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_test_scenarios__scenario_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs By Project */
        get: operations["list_runs_by_project_api_projects__project_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_api_runs__run_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description Live tail of agent_events for a run.
         *
         *     The connection stays open and polls the DB roughly every second, sending
         *     every new ``agent_event`` row as a Server-Sent Event. The stream ends
         *     with a ``done`` event once the run is in a terminal status (``completed``
         *     or ``failed``) and there are no more events to drain.
         */
        get: operations["stream_run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/feature-expectation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feature Expectation */
        get: operations["get_feature_expectation_api_runs__run_id__feature_expectation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Test Cases */
        get: operations["get_test_cases_api_runs__run_id__test_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/sandbox/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sandbox Files */
        get: operations["list_sandbox_files_api_runs__run_id__sandbox_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/sandbox/screenshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sandbox Screenshots
         * @description Ordered list of screenshot files for the run, newest last.
         *
         *     Each entry includes a download URL the frontend can use as an ``<img>``
         *     ``src``.
         */
        get: operations["list_sandbox_screenshots_api_runs__run_id__sandbox_screenshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/sandbox/files/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sandbox File
         * @description Stream a single artifact file.
         *
         *     Text-extension files (``.md``, ``.json``, ``.log`` etc.) are decoded and
         *     returned as ``text/plain; charset=utf-8``; everything else (PNG, JPEG,
         *     arbitrary binaries) is streamed verbatim with a guessed content-type so
         *     browsers can render images directly.
         */
        get: operations["get_sandbox_file_api_runs__run_id__sandbox_files__file_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/sandbox/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sandbox Status
         * @description Live status of the sandbox task backing this run.
         *
         *     Includes timeout / elapsed / remaining seconds so the frontend can
         *     show a deadline countdown and offer to extend.
         */
        get: operations["get_sandbox_status_api_runs__run_id__sandbox_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/sandbox/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extend Sandbox Timeout
         * @description Give the sandbox more time to finish.
         *
         *     Bumps the underlying sandbox task's ``timeout_seconds``. The runner
         *     re-reads the value on its next 2-second tick, so the change is live.
         *     Emits an ``agent_event`` so the frontend timeline reflects the
         *     extension.
         */
        post: operations["extend_sandbox_timeout_api_runs__run_id__sandbox_extend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/scripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Script Bundles */
        get: operations["list_script_bundles_api_runs__run_id__scripts_get"];
        put?: never;
        /**
         * Create Script Bundle
         * @description Kick off script generation for the given run.
         *
         *     Allowed only when the run is ``completed`` and there is at least
         *     one approved test case. Returns the fresh bundle row in
         *     ``pending`` status; the worker fires off in the background.
         */
        post: operations["create_script_bundle_api_runs__run_id__scripts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/scripts/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Script Bundle */
        get: operations["get_latest_script_bundle_api_runs__run_id__scripts_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/scripts/latest/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bundle Files */
        get: operations["list_bundle_files_api_runs__run_id__scripts_latest_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/scripts/latest/files/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bundle File */
        get: operations["get_bundle_file_api_runs__run_id__scripts_latest_files__file_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/scripts/latest/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Bundle Zip */
        get: operations["download_bundle_zip_api_runs__run_id__scripts_latest_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Executions */
        get: operations["list_executions_api_runs__run_id__executions_get"];
        put?: never;
        /**
         * Create Execution
         * @description Manually queue a test execution against the run's latest bundle.
         *
         *     Allowed only when the run is `completed` and has a successful
         *     bundle. Returns the new execution row in `queued` state; the
         *     worker fires off in the background.
         */
        post: operations["create_execution_api_runs__run_id__executions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/executions/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Execution */
        get: operations["latest_execution_api_runs__run_id__executions_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/{execution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Execution */
        get: operations["get_execution_api_executions__execution_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Execution
         * @description Cancel a queued or running execution.
         *
         *     Sends a cancel request to sandbox-svc (best-effort; the task may have
         *     already finished by the time we get there) and marks the execution as
         *     ``errored`` immediately so the UI stops showing it as in-flight.
         *     Returns 409 if the execution is already in a terminal state.
         */
        delete: operations["cancel_execution_api_executions__execution_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/{execution_id}/artifacts/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Execution Artifact
         * @description Proxy a file from the execution's sandbox-svc task.
         *
         *     Used by the UI to load failure screenshots, run-bundle logs, the
         *     HTML report, etc. We refuse anything outside ``output/`` to keep
         *     the surface small.
         */
        get: operations["get_execution_artifact_api_executions__execution_id__artifacts__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BundleFileList */
        BundleFileList: {
            /**
             * Bundle Id
             * Format: uuid
             */
            bundle_id: string;
            /** Task Id */
            task_id: string | null;
            /** Files */
            files: components["schemas"]["SandboxFileEntry"][];
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Message
             * @description User message text
             */
            message: string;
            /**
             * Thread Id
             * @description Conversation thread ID. Reuse the same ID to continue a conversation.
             */
            thread_id?: string;
            /**
             * Provider
             * @description LLM provider to use: 'openai', 'mistral', or 'anthropic'. Defaults to the server-configured provider.
             */
            provider?: ("openai" | "mistral" | "anthropic") | null;
            /**
             * Model
             * @description Model name for the chosen provider. Defaults to the server-configured model for that provider.
             */
            model?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Thread Id */
            thread_id: string;
            /** Content */
            content: string;
            /** Agent */
            agent?: string | null;
        };
        /** ExtendRequest */
        ExtendRequest: {
            /**
             * Extra Seconds
             * @description How many seconds to add to the sandbox's timeout budget.
             * @default 180
             */
            extra_seconds: number;
        };
        /** ExtendResponse */
        ExtendResponse: {
            /** Task Id */
            task_id: string;
            /** Previous Timeout Seconds */
            previous_timeout_seconds: number;
            /** Timeout Seconds */
            timeout_seconds: number;
            /** Added Seconds */
            added_seconds: number;
        };
        /** FeatureExpectationRead */
        FeatureExpectationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Version */
            version: number;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            status: components["schemas"]["FeatureExpectationStatus"];
            /** Feedback */
            feedback: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FeatureExpectationStatus
         * @enum {string}
         */
        FeatureExpectationStatus: "draft" | "approved" | "rejected";
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Decision
             * @description 'approve' or 'revise'
             */
            decision: string;
            /**
             * Feedback
             * @description Free-text feedback when revising
             */
            feedback?: string | null;
            /**
             * Workspace Outputs
             * @description Agent 2 workspace outputs. Only used when SANDBOX_ENABLED=false and the run is paused at the manual Agent 2 handoff interrupt.
             */
            workspace_outputs?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModelInfo */
        ModelInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Problem Statement */
            problem_statement: string;
            /** Target Users */
            target_users?: string | null;
            /** Tech Stack */
            tech_stack?: string | null;
            /** Additional Context */
            additional_context?: string | null;
        };
        /** ProjectRead */
        ProjectRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Problem Statement */
            problem_statement: string;
            /** Target Users */
            target_users: string | null;
            /** Tech Stack */
            tech_stack: string | null;
            /** Additional Context */
            additional_context: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Problem Statement */
            problem_statement?: string | null;
            /** Target Users */
            target_users?: string | null;
            /** Tech Stack */
            tech_stack?: string | null;
            /** Additional Context */
            additional_context?: string | null;
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /** Default Model */
            default_model: string;
            /** Models */
            models: components["schemas"]["ModelInfo"][];
        };
        /** ProvidersResponse */
        ProvidersResponse: {
            /** Providers */
            providers: components["schemas"]["ProviderInfo"][];
            /** Default Provider */
            default_provider: string;
        };
        /** RunCreateResponse */
        RunCreateResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Thread Id */
            thread_id: string;
        };
        /** RunRead */
        RunRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Test Scenario Id
             * Format: uuid
             */
            test_scenario_id: string;
            /** Thread Id */
            thread_id: string;
            status: components["schemas"]["RunStatus"];
            /** Current Node */
            current_node: string | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "agent1_running" | "agent1_review" | "agent2_running" | "agent3_running" | "agent3_review" | "completed" | "failed";
        /** SandboxFile */
        SandboxFile: {
            /** Path */
            path: string;
            /** Size */
            size: number;
        };
        /** SandboxFileEntry */
        SandboxFileEntry: {
            /** Path */
            path: string;
            /** Size */
            size: number;
        };
        /** SandboxFileList */
        SandboxFileList: {
            /** Task Id */
            task_id: string;
            /** Files */
            files: components["schemas"]["SandboxFile"][];
        };
        /** SandboxScreenshot */
        SandboxScreenshot: {
            /** Path */
            path: string;
            /** Url */
            url: string;
            /** Size */
            size: number;
        };
        /** SandboxScreenshotList */
        SandboxScreenshotList: {
            /** Task Id */
            task_id: string;
            /** Count */
            count: number;
            /** Screenshots */
            screenshots: components["schemas"]["SandboxScreenshot"][];
        };
        /** SandboxStatus */
        SandboxStatus: {
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Timeout Seconds */
            timeout_seconds?: number | null;
            /** Elapsed Seconds */
            elapsed_seconds?: number | null;
            /** Remaining Seconds */
            remaining_seconds?: number | null;
        };
        /**
         * TestCaseCategory
         * @enum {string}
         */
        TestCaseCategory: "happy" | "edge" | "corner";
        /** TestCaseRead */
        TestCaseRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Version */
            version: number;
            category: components["schemas"]["TestCaseCategory"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Preconditions */
            preconditions: string | null;
            /** Steps */
            steps: {
                [key: string]: unknown;
            }[];
            /** Expected Result */
            expected_result: string;
            /** Rationale */
            rationale: string | null;
            status: components["schemas"]["TestCaseStatus"];
            /** Feedback */
            feedback: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TestCaseStatus
         * @enum {string}
         */
        TestCaseStatus: "draft" | "approved" | "rejected";
        /**
         * TestExecutionDetail
         * @description Same as TestExecutionRead but with the per-test results array
         *     eagerly loaded. Used by the detail endpoint.
         */
        TestExecutionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Bundle Id
             * Format: uuid
             */
            bundle_id: string;
            status: components["schemas"]["TestExecutionStatus"];
            trigger: components["schemas"]["TestExecutionTrigger"];
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
            /** Sandbox Task Id */
            sandbox_task_id: string | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Results */
            results: components["schemas"]["TestExecutionResultRead"][];
        };
        /** TestExecutionRead */
        TestExecutionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Bundle Id
             * Format: uuid
             */
            bundle_id: string;
            status: components["schemas"]["TestExecutionStatus"];
            trigger: components["schemas"]["TestExecutionTrigger"];
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
            /** Sandbox Task Id */
            sandbox_task_id: string | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TestExecutionResultRead */
        TestExecutionResultRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Test Id */
            test_id: string;
            /** Test Case Id */
            test_case_id: string | null;
            outcome: components["schemas"]["TestOutcome"];
            /** Duration Ms */
            duration_ms: number | null;
            /** Failure Message */
            failure_message: string | null;
            /** Failure Trace */
            failure_trace: string | null;
            /** Screenshot Path */
            screenshot_path: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TestExecutionStatus
         * @enum {string}
         */
        TestExecutionStatus: "queued" | "running" | "passed" | "failed" | "errored";
        /**
         * TestExecutionTrigger
         * @enum {string}
         */
        TestExecutionTrigger: "auto" | "manual";
        /**
         * TestOutcome
         * @enum {string}
         */
        TestOutcome: "passed" | "failed" | "skipped" | "errored";
        /** TestScenarioCreate */
        TestScenarioCreate: {
            /** Title */
            title: string;
            /** Feature Description */
            feature_description: string;
            /** User Story */
            user_story: string;
            /** Acceptance Criteria */
            acceptance_criteria: string;
        };
        /** TestScenarioRead */
        TestScenarioRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Title */
            title: string;
            /** Feature Description */
            feature_description: string;
            /** User Story */
            user_story: string;
            /** Acceptance Criteria */
            acceptance_criteria: string;
            status: components["schemas"]["TestScenarioStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TestScenarioStatus
         * @enum {string}
         */
        TestScenarioStatus: "draft" | "in_progress" | "completed";
        /** TestScenarioUpdate */
        TestScenarioUpdate: {
            /** Title */
            title?: string | null;
            /** Feature Description */
            feature_description?: string | null;
            /** User Story */
            user_story?: string | null;
            /** Acceptance Criteria */
            acceptance_criteria?: string | null;
        };
        /** TestScriptBundleRead */
        TestScriptBundleRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Version */
            version: number;
            status: components["schemas"]["TestScriptBundleStatus"];
            /** Framework */
            framework: string | null;
            /** Language */
            language: string | null;
            /** Test Count */
            test_count: number | null;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            } | null;
            /** Sandbox Task Id */
            sandbox_task_id: string | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * TestScriptBundleStatus
         * @enum {string}
         */
        TestScriptBundleStatus: "pending" | "running" | "succeeded" | "failed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersResponse"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_test_scenarios_api_projects__project_id__test_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestScenarioRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_test_scenario_api_projects__project_id__test_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestScenarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestScenarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_scenario_api_test_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestScenarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_test_scenario_api_test_scenarios__scenario_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestScenarioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestScenarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_test_scenario_api_test_scenarios__scenario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_by_scenario_api_test_scenarios__scenario_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_test_scenarios__scenario_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_by_project_api_projects__project_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_runs__run_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_expectation_api_runs__run_id__feature_expectation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureExpectationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_cases_api_runs__run_id__test_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sandbox_files_api_runs__run_id__sandbox_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxFileList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sandbox_screenshots_api_runs__run_id__sandbox_screenshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxScreenshotList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sandbox_file_api_runs__run_id__sandbox_files__file_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sandbox_status_api_runs__run_id__sandbox_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extend_sandbox_timeout_api_runs__run_id__sandbox_extend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_script_bundles_api_runs__run_id__scripts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestScriptBundleRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_script_bundle_api_runs__run_id__scripts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestScriptBundleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_script_bundle_api_runs__run_id__scripts_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestScriptBundleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bundle_files_api_runs__run_id__scripts_latest_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleFileList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bundle_file_api_runs__run_id__scripts_latest_files__file_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_bundle_zip_api_runs__run_id__scripts_latest_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_executions_api_runs__run_id__executions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestExecutionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_execution_api_runs__run_id__executions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestExecutionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_execution_api_runs__run_id__executions_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestExecutionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_api_executions__execution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestExecutionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_execution_api_executions__execution_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestExecutionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_artifact_api_executions__execution_id__artifacts__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
